"""empty message

Revision ID: 6a24a9c8d289
Revises: 7637e3f8cdec
Create Date: 2023-12-31 01:23:59.541966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a24a9c8d289'
down_revision = '7637e3f8cdec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint("email", ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("email", 'users', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
